### ISSUE TITLE
Hetzner Load Balancer

### ISSUE THREAD

**Issue by marcuslindblom** [felipecruz91/k8s-hetzner#1]
Is there support for Hetzner load balancer when using these installer scripts? I'm having some issues to get things working.

**Comment by felipecruz91** [comment]
Hey @marcuslindblom, unfortunately, the Terraform scripts do not provision a Hetzner Load Balancer resource. 

I guess you could extend the Terraform scripts and provision one as described [here](https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/load_balancer).

**Comment by marcuslindblom** [comment]
@felipecruz91 ok, thanks!
I'm fairly new to Terraform scripts, where in your scripts would you put the load balancer resource?

**Comment by felipecruz91** [comment]
Assuming you want to load balance requests to the worker nodes, I'd probably add it in the [nodes.tf](https://github.com/felipecruz91/k8s-hetzner/blob/main/nodes.tf). This file describes the infrastructure of the K8s worker nodes.

Apart from the Load Balancer resource itself, you'll also have to add as many [Load Balancer targets](https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/load_balancer_target) as worker nodes your cluster has.

For instance, for a 3-node K8s cluster:

```tf
resource "hcloud_load_balancer_target" "load_balancer_target_worker_node_1" {
  type             = "server"
  load_balancer_id = hcloud_load_balancer.load_balancer.id
  server_id        = hcloud_server.worker_node_1.id
}

resource "hcloud_load_balancer_target" "load_balancer_target_worker_node_2" {
  type             = "server"
  load_balancer_id = hcloud_load_balancer.load_balancer.id
  server_id        = cloud_server.worker_node_2.id
}

resource "hcloud_load_balancer_target" "load_balancer_target_worker_node_2" {
  type             = "server"
  load_balancer_id = hcloud_load_balancer.load_balancer.id
  server_id        = cloud_server.worker_node_3.id
}
```

**Comment by marcuslindblom** [comment]
@felipecruz91 Ok, thanks again!

Do you know if it's possible to create services manually in the load balancer in Hetzner cloud console to get it working?
Or do I need to modify how the cluster is created to get the load balancer to work at all?

If I create services manually and point them to the correct nodeports I get healthy services but the External IP just says pending. Maybe I could set the external ip to the load balancer ip to get it working?
